package:
  name: marvin
  version: "4.4.dev1"

source:
  # path to source ... modify if necessary
  path: # C:\Users\swaterbu\clones\marvin

build:
  number: 1
  entry_points:
          - marvin = marvin.__main__:main

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - python {{PY_VER}}
    - menuinst
    - pangalactic.node >=4.4.dev1

about:
  # home: [url]
  # license: NASA
  # license_file: LICENSE

app:
  entry: marvin
  icon: pangalacticon.ico
  summary: "Marvin"

