package:
  name: gargleblaster
  version: "4.4.dev2"

source:
  # path to source ... modify if necessary
  path: # C:\Users\waterbug\clones\gargleblaster

build:
  number: 1
  entry_points:
          - gargleblaster = gargleblaster.__main__:main

requirements:
  build:
    - python {{PY_VER}}
    - setuptools

  run:
    - python {{PY_VER}}
    - menuinst
    - pangalactic.node >=4.4.dev2

about:
  # home: [url]
  # license: NASA
  # license_file: LICENSE

app:
  entry: gargleblaster
  icon: pangalacticon.ico
  summary: "Gargleblaster"

